fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

print('\n', fruits)
print('Count apple = ', fruits.count('apple'))
print('Count tangerine = ', fruits.count('tangerine'))
print('Count banana = ', fruits.count('banana'))
print('Banana at index', fruits.index('banana'))
print('Banana at index with starting position 4', fruits.index('banana', 4))
print('Reverse lists')
fruits.reverse()
print(fruits)
print('Add grape on lists')
fruits.append('grape')
print(fruits)
print('Sorting lists')
fruits.sort()
print(fruits)
print('Remove last item on list which is', fruits.pop())
print(fruits)
